package bank.tessera.ledger.loader;

import java.time.LocalDate;
import java.util.Map;
import java.util.Objects;

/**
 * The first line of a dataset stream: what the loader needs before the first account.
 *
 * <p>Everything here is decided by the emitter and not by this module. The base currency is
 * {@code seeding.BaseCurrency}'s answer, the treasury reference is generated by the population one
 * index past the last customer, and the cohort medians come out of the model. A loader that computed
 * any of them would be a second opinion, and the two halves of the workload strand would be
 * describing different banks.
 *
 * @param cohortMedians the median transfer size per cohort, in minor units - what an opening balance
 *     is scaled against
 */
public record Header(
        String modelId,
        String modelVersion,
        String modelDigest,
        long seed,
        double scale,
        LocalDate from,
        LocalDate to,
        int customers,
        int accountsPerCustomer,
        String baseCurrency,
        String customerAccountType,
        String treasuryAccountType,
        Map<String, Long> cohortMedians,
        String treasuryCustomerRef,
        String treasuryAccountRef) {

    public Header {
        Objects.requireNonNull(modelDigest, "modelDigest");
        Objects.requireNonNull(from, "from");
        Objects.requireNonNull(to, "to");
        Objects.requireNonNull(baseCurrency, "baseCurrency");
        Objects.requireNonNull(treasuryAccountRef, "treasuryAccountRef");
        cohortMedians = Map.copyOf(Objects.requireNonNull(cohortMedians, "cohortMedians"));
        if (to.isBefore(from)) {
            throw new IllegalArgumentException("A dataset that ends on " + to + " and begins on " + from);
        }
    }

    /**
     * The date every account is opened and funded on.
     *
     * <p>The day before the range, so that no opening entry shares a business date with a drawn one
     * and no funding reference can collide with a transfer reference the population minted - both are
     * {@code TB} then the date then a sequence, and the date is what keeps the two apart.
     */
    public LocalDate openingDate() {
        return from.minusDays(1);
    }
}
