// Package seeding opens and funds the accounts a run is about to use.
//
// It runs to completion before the first scheduled event is sent, and it is deliberately not part
// of the measurement: an opening balance is a transfer like any other, and counting a few thousand
// of them as offered load would put a spike at the start of every run that has nothing to do with
// the day the model describes.
//
// Nothing here invents a reference. Every account comes from the schedule the run is about to
// execute, and the treasury the funding is debited from is generated by the population itself, one
// index past the last customer.
package seeding

import (
	"context"
	"fmt"
	"iter"
	"sync"
	"time"

	"github.com/k-napiontek/tessera-bank/workload/internal/arrivals"
	"github.com/k-napiontek/tessera-bank/workload/internal/bankday"
	"github.com/k-napiontek/tessera-bank/workload/internal/client"
	"github.com/k-napiontek/tessera-bank/workload/internal/money"
	"github.com/k-napiontek/tessera-bank/workload/internal/population"
)

// Account is one account the run will use.
type Account struct {
	CustomerRef string
	AccountRef  string
	// Type is the ledger's account type. Customers hold a LIABILITY of the bank; the treasury is an
	// ASSET, so debiting it to fund a customer increases it and it never needs an overdraft.
	Type string
}

// Types the ledger's contract enumerates. Only two are used here.
const (
	Liability = "LIABILITY"
	Asset     = "ASSET"
)

// BaseCurrency is the currency every account in a run is opened in.
//
// **The model's currency mix cannot be realised against this estate, and this is where that is
// decided rather than discovered.** The ledger fixes an account's currency when it is opened and
// requires a transfer to be in the currency of both accounts; the model draws a currency per
// transfer from a mix of up to five, and gives each customer two accounts. A customer whose
// accounts are PLN and EUR still cannot send the USD the mix draws, and pairing two accounts drawn
// independently would leave most transfers with no currency in common at all.
//
// So the estate is opened in one currency - the heaviest in the model, computed rather than
// assumed - and a transfer drawn in another goes in that one and is counted as substituted. The
// alternative is a run in which most transfers are 422 CURRENCY_MISMATCH: the ledger working
// correctly, the driver measuring itself, and a rejection column that says nothing about the bank.
func BaseCurrency(people population.Population) (money.Currency, error) {
	weight := map[money.Currency]float64{}
	for _, cohort := range people.Cohorts() {
		share := people.EventShare(cohort.ID)
		for _, currency := range cohort.Currencies {
			weight[currency.Value] += share * currency.Weight
		}
	}

	var heaviest money.Currency
	var best float64
	for currency, total := range weight {
		// Ties broken by the currency code so that a model with two equal currencies still seeds
		// the same estate twice. A run that is reproducible except for its currency is not.
		if total > best || (total == best && currency < heaviest) {
			heaviest, best = currency, total
		}
	}
	if heaviest == "" {
		return "", fmt.Errorf("seeding: the model declares no currency to open accounts in")
	}
	if !money.Valid(heaviest) {
		return "", fmt.Errorf("seeding: %s is not a currency this estate can carry", heaviest)
	}
	return heaviest, nil
}

// Plan is every account the schedule will touch, in first-use order, with the treasury first.
//
// Walked from the same seed and model the run will use, so the estate is seeded for exactly the day
// that is about to be executed - no more, which would leave the ledger holding accounts nothing
// ever used, and no less, which would spend the run collecting 404s.
func Plan(people population.Population, events iter.Seq[arrivals.Event], seed uint64, date bankday.Date) []Account {
	treasuryCustomer, treasuryAccount := people.Treasury()
	plan := []Account{{CustomerRef: treasuryCustomer, AccountRef: treasuryAccount, Type: Asset}}

	seen := map[string]bool{treasuryAccount: true}
	add := func(accountRef string) {
		if accountRef == "" || seen[accountRef] {
			return
		}
		customerRef, found := people.CustomerOf(accountRef)
		if !found {
			return
		}
		seen[accountRef] = true
		plan = append(plan, Account{CustomerRef: customerRef, AccountRef: accountRef, Type: Liability})
	}

	for event := range events {
		action := people.Draw(seed, event.Seq, date)
		add(action.AccountRef)
		add(action.CounterpartyRef)
	}
	return plan
}

// PlanAll is every account the population declares, treasury first.
//
// Plan is the right answer for a run measured on its own: it opens what the schedule touches and no
// more, so a compressed day does not spend its time standing up two million accounts to use nine
// thousand. This is the right answer for a run that is going to be **reconciled**.
// mainframe/data/generate.py writes an ACCTREC for every account the stream opens, so an account the
// day happened not to touch is present on the master and absent from the ledger - a
// MISSING_IN_LEDGER break per account, and a reconciliation whose real findings are buried under
// tens of thousands of them. The two sides have to describe the same bank before a break means
// anything.
//
// Ordering and membership come from population.Accounts, which already yields the treasury first,
// so nothing here decides either.
func PlanAll(people population.Population) []Account {
	plan := []Account{}
	for holding := range people.Accounts() {
		accountType := Liability
		if holding.Treasury {
			accountType = Asset
		}
		plan = append(plan, Account{
			CustomerRef: holding.CustomerRef,
			AccountRef:  holding.AccountRef,
			Type:        accountType,
		})
	}
	return plan
}

// Opening is what every account is funded with.
//
// A multiple of the largest transfer the model can draw, so that a short run is a study of the
// estate under load rather than a study of INSUFFICIENT_FUNDS. Accounts do drift - money moves
// between them and the total is conserved - and a run long enough to drain one has found something
// worth knowing rather than a fixture that needs a bigger number.
func Opening(people population.Population, currency money.Currency) (money.Amount, error) {
	var largest int64
	for _, cohort := range people.Cohorts() {
		if cohort.Amount.MaxMinor > largest {
			largest = cohort.Amount.MaxMinor
		}
	}
	if largest <= 0 {
		return money.Amount{}, fmt.Errorf("seeding: the model draws no positive amount to size an opening balance from")
	}
	return money.New(largest*openingMultiple, currency)
}

// openingMultiple is how many of the largest possible transfer an account is opened with.
const openingMultiple = 20

// Sender is the half of client.Sender seeding needs. Named here rather than taken as a concrete
// type so that a test can seed an estate that does not exist.
type Sender interface {
	Send(ctx context.Context, request client.Request, intended time.Time) client.Result
}

// Report is what seeding did.
type Report struct {
	Opened      int
	AlreadyOpen int
	Funded      int
	Replayed    int
	Failed      int
}

// Total is how many accounts were dealt with, however they turned out.
func (r Report) Total() int { return r.Opened + r.AlreadyOpen + r.Failed }

// Run opens and funds every account in the plan.
//
// The plan's first entry is the treasury and it is opened alone, before anything else: funding
// debits it, and a worker that raced ahead would be funding from an account that did not exist yet.
//
// date is the business date the run is about to execute. Funding is dated the day before it - see
// client.Fund and F-103.
func Run(
	ctx context.Context,
	sender Sender,
	plan []Account,
	opening money.Amount,
	workers int,
	date bankday.Date,
) (Report, error) {
	if len(plan) == 0 {
		return Report{}, fmt.Errorf("seeding: nothing to seed")
	}
	if workers < 1 {
		workers = 1
	}

	treasury := plan[0]
	if treasury.Type != Asset {
		return Report{}, fmt.Errorf("seeding: the first account in a plan is the treasury, and this one is %s", treasury.Type)
	}
	report := Report{}
	opened, err := open(ctx, sender, treasury, opening.Currency)
	if err != nil {
		return report, fmt.Errorf("seeding: the treasury could not be opened: %w", err)
	}
	count(&report, opened)

	var mu sync.Mutex
	var group sync.WaitGroup
	work := make(chan Account)

	for worker := 0; worker < workers; worker++ {
		group.Add(1)
		go func() {
			defer group.Done()
			for account := range work {
				outcome, err := open(ctx, sender, account, opening.Currency)
				mu.Lock()
				if err != nil {
					report.Failed++
					mu.Unlock()
					continue
				}
				count(&report, outcome)
				mu.Unlock()

				// Funded even when the account was already open: a re-run against a seeded estate
				// replays the funding under the same key rather than crediting it twice.
				funded, err := client.Fund(
					treasury.AccountRef, account.AccountRef, account.CustomerRef, opening, date)
				if err != nil {
					mu.Lock()
					report.Failed++
					mu.Unlock()
					continue
				}
				result := sender.Send(ctx, funded, time.Now())
				mu.Lock()
				switch result.Outcome {
				case client.Posted:
					report.Funded++
				case client.Replayed:
					report.Replayed++
				default:
					report.Failed++
				}
				mu.Unlock()
			}
		}()
	}

	for _, account := range plan[1:] {
		select {
		case <-ctx.Done():
			close(work)
			group.Wait()
			return report, ctx.Err()
		case work <- account:
		}
	}
	close(work)
	group.Wait()

	if report.Failed > 0 {
		// A run against an estate that could not be seeded is not a run: every event it sends will
		// be a 404 on an account that was never opened, and the report would read as the ledger
		// refusing traffic.
		return report, fmt.Errorf("seeding: %d of %d accounts could not be prepared", report.Failed, len(plan))
	}
	return report, nil
}

func open(ctx context.Context, sender Sender, account Account, currency money.Currency) (client.Outcome, error) {
	request, err := client.OpenAccount(account.CustomerRef, account.AccountRef, account.Type, currency)
	if err != nil {
		return client.Unknown, err
	}
	result := sender.Send(ctx, request, time.Now())
	switch {
	case result.Outcome == client.Posted:
		return client.Posted, nil
	case result.Status == 409:
		// The reference already exists, which openAccount's own description calls the idempotent
		// case: "opening a reference that already exists is a 409 rather than a second account".
		return client.Rejected, nil
	default:
		return result.Outcome, fmt.Errorf("opening %s answered %d", account.AccountRef, result.Status)
	}
}

func count(report *Report, outcome client.Outcome) {
	if outcome == client.Posted {
		report.Opened++
		return
	}
	report.AlreadyOpen++
}
