package bank.tessera.ledger.loader;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import bank.tessera.ledger.loader.LedgerRows.PostingRow;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Test;

/**
 * The loader's arithmetic, against the stream {@code workload-dataset} actually produces.
 *
 * <p>The fixture is generated by that command and a Go test regenerates and compares it, so these
 * tests run against the real shape rather than against a hand-written approximation of it - which is
 * the only kind that stays true.
 */
class DatasetLoaderTest {

    static final String FIXTURE = "/sample-stream.ndjson";

    static InputStream fixture() {
        InputStream stream = DatasetLoaderTest.class.getResourceAsStream(FIXTURE);
        if (stream == null) {
            throw new IllegalStateException("The sample stream is missing from the test resources.");
        }
        return stream;
    }

    static Loaded load() throws IOException {
        RecordingSink sink = new RecordingSink();
        DatasetLoader loader = new DatasetLoader(sink, 1_000_000);
        try (InputStream in = fixture()) {
            DatasetReader.read(in, loader);
        }
        return new Loaded(sink, loader.finish());
    }

    record Loaded(RecordingSink sink, LoadSummary summary) {}

    @Test
    void everyAccountTheStreamNamesIsOpenedWithABalanceRow() throws IOException {
        Loaded loaded = load();

        // 200 customers with two accounts each, and the treasury.
        assertThat(loaded.sink().accounts).hasSize(401);
        assertThat(loaded.summary().count(Counter.ACCOUNTS_OPENED)).isEqualTo(401);
        assertThat(loaded.sink().balances).hasSize(401);
        assertThat(loaded.sink().accounts)
                .allSatisfy(account -> {
                    assertThat(account.status()).isEqualTo("OPEN");
                    assertThat(account.currency()).isEqualTo("PLN");
                    // Null, not zero: forbidden and "may reach exactly zero" are different statements.
                    assertThat(account.overdraftLimitMinor()).isNull();
                    assertThat(account.openedDate()).isEqualTo(loaded.summary().header().openingDate());
                });
    }

    @Test
    void exactlyOneAccountIsTheTreasuryAndItIsTheOnlyAsset() throws IOException {
        Loaded loaded = load();

        assertThat(loaded.sink().accounts)
                .filteredOn(account -> account.accountType().equals("ASSET"))
                .singleElement()
                .satisfies(treasury ->
                        assertThat(treasury.reference()).isEqualTo(loaded.summary().header().treasuryAccountRef()));
        assertThat(loaded.sink().accounts)
                .filteredOn(account -> !account.accountType().equals("ASSET"))
                .allSatisfy(account -> assertThat(account.accountType()).isEqualTo("LIABILITY"));
    }

    /**
     * An opening balance is a transfer, not a number typed into a column. That is what a double-entry
     * ledger is, and a loader that wrote a balance row without the postings behind it would produce a
     * ledger whose own reconciliation refuses it.
     */
    @Test
    void anOpeningBalanceIsPostedFromTheTreasury() throws IOException {
        Loaded loaded = load();

        assertThat(loaded.summary().count(Counter.FUNDING_ENTRIES)).isEqualTo(400);
        assertThat(loaded.sink().entries)
                .filteredOn(entry -> "OPENING BALANCE".equals(entry.referenceText()))
                .hasSize(400)
                .allSatisfy(entry -> assertThat(entry.valueDate())
                        .isEqualTo(loaded.summary().header().openingDate()));

        String treasury = loaded.summary().header().treasuryAccountRef();
        assertThat(loaded.sink().postings)
                .filteredOn(posting -> posting.accountRef().equals(treasury))
                .hasSize(400)
                .allSatisfy(posting -> assertThat(posting.direction()).isEqualTo("DEBIT"));
    }

    @Test
    void theTreasuryIsNotFundedByItself() throws IOException {
        Loaded loaded = load();
        String treasury = loaded.summary().header().treasuryAccountRef();

        assertThat(loaded.sink().postings)
                .filteredOn(posting -> posting.accountRef().equals(treasury) && posting.direction().equals("CREDIT"))
                .isEmpty();
    }

    /**
     * The invariant the database enforces with a deferred constraint trigger. Checking it here as
     * well means a loader defect is a failing unit test rather than a load that dies four million
     * rows in with a message naming one entry.
     */
    @Test
    void everyEntryBalances() throws IOException {
        Loaded loaded = load();

        Map<String, Long> net = new HashMap<>();
        for (PostingRow posting : loaded.sink().postings) {
            long signed = posting.direction().equals("DEBIT") ? posting.amountMinor() : -posting.amountMinor();
            net.merge(posting.entryRef(), signed, Long::sum);
        }
        assertThat(net).isNotEmpty();
        assertThat(net).allSatisfy((entryRef, difference) ->
                assertThat(difference).describedAs("entry %s", entryRef).isZero());
    }

    /**
     * A funding reference is minted here and a transfer reference is drawn by the population. They
     * share a format, and the only thing keeping them apart is that the opening date falls outside
     * the range. A collision would be a primary-key violation halfway through a load, or worse, two
     * different movements under one reference.
     */
    @Test
    void noTwoEntriesShareAReference() throws IOException {
        Loaded loaded = load();

        assertThat(loaded.sink().entries)
                .extracting(LedgerRows.EntryRow::reference)
                .doesNotHaveDuplicates()
                .allSatisfy(reference -> assertThat(reference).matches("^TB[0-9]{18}$"));
    }

    @Test
    void aCheckpointIsTakenAtTheEndOfEveryBusinessDate() throws IOException {
        Loaded loaded = load();

        // The opening date, then each of the two dates the fixture covers, then the closing balances.
        assertThat(loaded.sink().checkpoints)
                .contains(loaded.summary().header().openingDate())
                .contains(loaded.summary().header().from())
                .contains(loaded.summary().header().to());
    }

    @Test
    void aStreamWithNoHeaderIsRefused() {
        String orphan = "{\"kind\":\"action\",\"date\":\"2026-03-02\",\"seq\":1,\"atMillis\":0,"
                + "\"cohort\":\"retail\",\"operation\":\"getBalance\",\"customerRef\":\"CU0000000001\","
                + "\"accountRef\":\"TB00000000000001\"}\n";

        assertThatThrownBy(() -> DatasetReader.read(bytes(orphan), new RecordingLoader()))
                .isInstanceOf(IOException.class)
                .hasMessageContaining("before the population header");
    }

    /**
     * The emitter and this reader are one contract in two languages with no schema between them. A
     * field added on one side and ignored on the other is a column silently dropped from a five
     * million row load, and the load would finish and look right.
     */
    @Test
    void aFieldThisReaderDoesNotKnowIsRefused() {
        String withExtra = "{\"kind\":\"population\",\"modelId\":\"X\",\"modelVersion\":\"1\","
                + "\"modelDigest\":\"d\",\"seed\":1,\"scale\":1,\"from\":\"2026-03-02\",\"to\":\"2026-03-02\","
                + "\"customers\":1,\"accountsPerCustomer\":1,\"baseCurrency\":\"PLN\","
                + "\"customerAccountType\":\"LIABILITY\",\"treasuryAccountType\":\"ASSET\",\"cohorts\":[],"
                + "\"treasuryCustomerRef\":\"CU0000000001\",\"treasuryAccountRef\":\"TB00000000000001\","
                + "\"somethingNew\":42}\n";

        assertThatThrownBy(() -> DatasetReader.read(bytes(withExtra), new RecordingLoader()))
                .isInstanceOf(IOException.class)
                .hasMessageContaining("somethingNew");
    }

    @Test
    void openingTheSameAccountTwiceIsRefused() throws IOException {
        RecordingSink sink = new RecordingSink();
        DatasetLoader loader = new DatasetLoader(sink, 1_000_000);
        try (InputStream in = fixture()) {
            DatasetReader.read(in, loader);
        }

        OpenAccount again = firstOpen();
        assertThatThrownBy(() -> loader.open(again))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("twice");
    }

    private OpenAccount firstOpen() throws IOException {
        RecordingLoader recorder = new RecordingLoader();
        try (InputStream in = fixture()) {
            DatasetReader.read(in, recorder);
        }
        return recorder.firstOpen;
    }

    private static InputStream bytes(String text) {
        return new ByteArrayInputStream(text.getBytes(StandardCharsets.UTF_8));
    }

    /** Keeps the first of each kind so a test can replay one line on its own. */
    static final class RecordingLoader implements DatasetVisitor {
        Header header;
        OpenAccount firstOpen;

        @Override
        public void population(Header incoming) {
            header = incoming;
        }

        @Override
        public void open(OpenAccount account) {
            if (firstOpen == null) {
                firstOpen = account;
            }
        }

        @Override
        public void action(DrawnAction action) {
            // Nothing: this recorder exists to reach the header and the first account.
        }
    }
}
